### ISSUE TITLE
Getting error of no such element

### ISSUE THREAD

**Issue by wasi-master** [marcus604/LastFMDuplicateDeleter#9]
This is the error I get
```python
Traceback (most recent call last):
  File "C:\Users\Wasi Master\Documents\GitHub\LastFMDuplicateDeleter\app\main.py", line 299, in <module>
    main()
  File "C:\Users\Wasi Master\Documents\GitHub\LastFMDuplicateDeleter\app\main.py", line 168, in main
    signIn(browser, userConfig["username"], password)
  File "C:\Users\Wasi Master\Documents\GitHub\LastFMDuplicateDeleter\app\main.py", line 77, in signIn
    userField = browser.find_element("id","id_username_or_email")
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="id_username_or_email"]"}
```

I'm running it on my profile ([https://www.last.fm/user/WasiMaster](https://www.last.fm/user/WasiMaster`)), I don't know what could be the cause of this, and I can't provide a reproducible example since I can't share my credentials.

**Comment by wasi-master** [comment]
Doing a dry run with 5 pages works fine

**Comment by wasi-master** [comment]
Okay now it works again huh, I guess it must be a one time issue

**Comment by marcus604** [comment]
Could be a similar thing as issue #1 where a new pop-up box or page is being displayed intermittently when going to the login page.

Created #10 to help debug these issues
